In [ ]:
import pandas as pd
import numpy as np

impact_data_filepath = r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\impact_catalog\impactevents-202408.xlsx'

dfb = pd.read_excel(impact_data_filepath, engine='openpyxl', sheet_name=0)

disaster_types = ['Flood', 'Drought']
dfb_f1 = dfb[dfb['disaster type'].isin(disaster_types)]

ea_cntr = ['Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Rwanda', 'Somalia', 'South Sudan', 'Sudan (the)', 'Tanzania, United Republic of']

dfb_fl_ea = dfb_f1[dfb_f1['country'].isin(ea_cntr)]

dfb_fl_ea_map = dfb_fl_ea[['sno', 'date of event', 'country', 'reported region/places', 'report type']]

dfb_fl_ea_map['loc_str1'] = dfb_fl_ea_map['reported region/places'].str.replace(' and ', ',', regex=False)
dfb_fl_ea_map['loc_str2'] = dfb_fl_ea_map['loc_str1'].str.replace(' & ', ',', regex=False)
dfb_fl_ea_map['loc_str3'] = dfb_fl_ea_map['loc_str2'].str.replace('&', ',', regex=False)
dfb_fl_ea_map['loc_str4'] = dfb_fl_ea_map['loc_str3'].str.replace(';', ',', regex=False)
dfb_fl_ea_map['loc_list'] = dfb_fl_ea_map['loc_str4'].str.split(',')

df_fl = dfb_fl_ea_map.explode('loc_list')

df_fl['row_idx'] = ['fl_' + str(idx) for idx in range(len(df_fl))]

df_fl['loc_list_a'] = df_fl['loc_list'].str.strip()

df3_fl = df_fl[['sno', 'date of event', 'country', 'loc_list', 'loc_list_a', 'reported region/places', 'row_idx', 'report type']]

df3_fl = df3_fl.reset_index(drop=True)

output_filepath = 'ea_flood_drought_location_processed.csv'
df3_fl.to_csv(output_filepath, index=False)

print(f"Processed data saved to: {output_filepath}")


#df3_fl.to_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_ibf_data_resources/impact/em-dat/ea_flood_location.csv',index=False)
#d
#df3_fl.info()


# db=pd.read_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_ibf_data_resources/impact/em-dat/ea_flood_missing_location.csv')

# db['code']=db['Dis No'].str.split('-').str[-1]

# db['loc_list'] = db['Location'].str.split(',')
# db1=db.explode('loc_list')
# #db2=db1.drop_duplicates('loc_list')

# db2=db1.drop_duplicates('code')
# code_list=db2['code'].tolist()
# db1.to_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_ibf_data_resources/impact/em-dat/ea_flood_missing_location_v1.csv')

Processed data saved to: ea_flood_drought_location_processed.csv

C:\Users\HP 820\AppData\Local\Temp\ipykernel_14188\2206630119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str1'] = dfb_fl_ea_map['reported region/places'].str.replace(' and ', ',', regex=False)
C:\Users\HP 820\AppData\Local\Temp\ipykernel_14188\2206630119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str2'] = dfb_fl_ea_map['loc_str1'].str.replace(' & ', ',', regex=False)
C:\Users\HP 820\AppData\Local\Temp\ipykernel_14188\2206630119.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str3'] = dfb_fl_ea_map['loc_str2'].str.replace('&', ',', regex=False)

In [2]:
dfb_fl_ea.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 62 to 259
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sno                     17 non-null     int64
 1   date of event           17 non-null     object
 2   country                 17 non-null     object
 3   report type             17 non-null     object
 4   corrected_report_type   17 non-null     int64
 5   disaster type           17 non-null     object
 6   reported region/places  17 non-null     object
 7   reported loss if any    17 non-null     object
 8   report link             17 non-null     object
dtypes: int64(2), object(7)
memory usage: 1.3+ KB

In [3]:
db = pd.read_csv(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\impact_catalog\ea_flood_drought_location_processed.csv')

# db['code'] = db['sno'].str.split('-').str[-1]

db['loc_list'] = db['reported region/places'].str.split(',')
db1 = db.explode('loc_list')
db2=db1.drop_duplicates('loc_list')

db2 = db1.drop_duplicates('reported region/places')
code_list = db2['reported region/places'].tolist()

db1.to_csv('ea_flood_drought_missing_location_v1.csv')

In [4]:
db2

,sno,date of event,country,loc_list,loc_list_a,reported region/places,row_idx,report type
0,63,20241204,Somalia,Lower Shabelle (Juba camp in Weydow,Lower Shabelle (Juba camp in Weydow,"Lower Shabelle (Juba camp in Weydow, Garasbale...",fl_0,Drought Impact Report
2,106,20241117,Somalia,East Africa,East Africa,East Africa,fl_2,1 - ongoing event
3,145,20241026,South Sudan,Various regions,Various regions,"Various regions, communities on higher ground",fl_3,UN Report
5,174,20241018,South Sudan,42 counties,42 counties,"42 counties, Abyei, Northern Bahr el Ghazal, U...",fl_5,South Sudan Floods Snapshot
9,175,20241017,South Sudan,38 counties,38 counties,"38 counties, Jonglei, Northern Bahr el Ghazal,...",fl_9,South Sudan Floods - Emergency Appeal (MDRSS014)
15,176,20241019,South Sudan,Northern Bahr el Ghazal,Northern Bahr el Ghazal,"Northern Bahr el Ghazal, Unity, 42 counties ac...",fl_15,Over 1 million people affected by flooding in ...
18,178,20241018,South Sudan,South Sudan,South Sudan,South Sudan,fl_18,Satellite Image Report
19,217,20241001,Somalia,National,National,"National, Somalia",fl_19,Drought Risk
21,231,20241002,South Sudan,Mangar Ajak,Mangar Ajak,"Mangar Ajak, Gogrial West County",fl_21,Flood Displacement
23,232,20241001,South Sudan,Akon International Airport,Akon International Airport,"Akon International Airport, Gogrial West Count...",fl_23,Floods
26,233,20241001,South Sudan,South Sudan (White Nile and Tributaries),South Sudan (White Nile,South Sudan (White Nile and Tributaries),fl_26,Flood Assistance
28,234,20241003,South Sudan,Nationwide (Jonglei,Nationwide (Jonglei,"Nationwide (Jonglei, Upper Nile, Unity, Warrap...",fl_28,National Disaster Declaration
34,236,20240919,Ethiopia,Addis Ababa,Addis Ababa,"Addis Ababa, rural areas of Ethiopia",fl_34,Flood Warning Testing
36,257,20240812,Ethiopia,Gambella Region (4 districts),Gambella Region (4 districts),Gambella Region (4 districts),fl_36,Flooding in Western Ethiopia
37,258,20240908,Kenya,Kajiado,Kajiado,"Kajiado, Laikipia",fl_37,Drought affecting Maasai and other cattle herders
39,259,20240907,Kenya,Kilifi (Mariakani Ward),Kilifi (Mariakani Ward),Kilifi (Mariakani Ward),fl_39,Drought affecting farmers in Kilifi
40,262,202409,South Sudan,Lakes State,Lakes State,"Lakes State, Unity State, Sudd region",fl_40,Floods causing mass population displacement

In [5]:
import geopandas as gp

gaul_adm2=gp.read_file('C:/Users/HP 820/loan_prediction/ea-ibf-climada/data_sources/202501-impact-events/202501-impact-events/shpfiles/ea_adm2_gaul.shp')

In [6]:
gaul_adm2

,gml_id,fid,ADM2_CODE,ADM2_NAME,ADM1_CODE,ADM1_NAME,STATUS,DISP_AREA,ADM0_CODE,ADM0_NAME,geometry
0,None,20,32854,Al Mahabishah,3418,Hajjah,Member State,NO,269,Yemen,"MULTIPOLYGON (((43.45552 15.97692, 43.45554 15..."
1,None,8004,12847,Ouadda,856,Haute-Kotto,Member State,NO,49,Central African Republic,"POLYGON ((23.2875 8.76171, 23.28112 8.75005, 2..."
2,None,8005,12848,Yalinga,856,Haute-Kotto,Member State,NO,49,Central African Republic,"POLYGON ((24.2722 8.27699, 24.2739 8.27343, 24..."
3,None,57,32877,Al Makhadir,3419,Ibb,Member State,NO,269,Yemen,"POLYGON ((44.26976 14.20502, 44.26981 14.20496..."
4,None,59,32853,Al Miftah,3418,Hajjah,Member State,NO,269,Yemen,"POLYGON ((43.54572 15.9774, 43.55705 15.97485,..."
...,...,...,...,...,...,...,...,...,...,...,...
1449,None,33989,32849,Abs,3418,Hajjah,Member State,NO,269,Yemen,"POLYGON ((43.22042 16.18735, 43.22144 16.18402..."
1450,None,34013,32850,Aflah Al Yaman,3418,Hajjah,Member State,NO,269,Yemen,"POLYGON ((43.44169 15.98401, 43.44304 15.98109..."
1451,None,34019,32851,Aflah Ash Shawm,3418,Hajjah,Member State,NO,269,Yemen,"POLYGON ((43.43349 16.07773, 43.43851 16.07462..."
1452,None,34039,32852,Al Jamimah,3418,Hajjah,Member State,NO,269,Yemen,"POLYGON ((43.5759 16.09728, 43.57911 16.09281,..."
1453,None,34141,32855,Al Maghrabah,3418,Hajjah,Member State,NO,269,Yemen,"POLYGON ((43.70865 15.93842, 43.70853 15.93832..."

In [7]:
import geopandas as gp
import pandas as pd

adm0=gp.read_file(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\data_sources\202501-impact-events\202501-impact-events\shpfiles\ea_adm0_geoboundaries.shp')
adm1=gp.read_file(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\data_sources\202501-impact-events\202501-impact-events\shpfiles\ea_adm1_geoboundaries.shp')
adm2=gp.read_file(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\data_sources\202501-impact-events\202501-impact-events\shpfiles\ea_adm2_geoboundaries.shp')

db=pd.concat([adm0,adm1,adm2])

db1=db.drop_duplicates('shapeID')
db1.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1155 entries, 0 to 971
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   shapeName   1155 non-null   object
 1   shapeISO    1151 non-null   object
 2   shapeID     1155 non-null   object
 3   shapeGroup  1155 non-null   object
 4   shapeType   1155 non-null   object
 5   geometry    1155 non-null   geometry
dtypes: geometry(1), object(5)
memory usage: 63.2+ KB

In [8]:
db1=db[db['shapeGroup']=='SDN']
#db1.shapeName.tolist()
db2=db1.sort_values('shapeName')
db3=db2[['shapeName','shapeType','shapeID']]
pd.set_option('display.max_columns', 4)
pd.set_option('display.max_rows', 200)
print(db3)

                shapeName shapeType              shapeID
522             Abu Hamed      ADM2    SDN-ADM2-3_0_0-B8
544            Abu Houjar      ADM2   SDN-ADM2-3_0_0-B30
654             Abu Jabra      ADM2  SDN-ADM2-3_0_0-B140
576           Abu Jubaiha      ADM2   SDN-ADM2-3_0_0-B62
624           Abu Karinka      ADM2  SDN-ADM2-3_0_0-B110
650             Abu Zabad      ADM2  SDN-ADM2-3_0_0-B136
640        Abyei - Muglad      ADM2  SDN-ADM2-3_0_0-B126
584        Abyei PCA Area      ADM2   SDN-ADM2-3_0_0-B70
655                 Adila      ADM2  SDN-ADM2-3_0_0-B141
567                  Agig      ADM2   SDN-ADM2-3_0_0-B53
635               Ailliet      ADM2  SDN-ADM2-3_0_0-B121
583              Al Buram      ADM2   SDN-ADM2-3_0_0-B69
531               Al Daba      ADM2   SDN-ADM2-3_0_0-B17
680             Al Mafaza      ADM2  SDN-ADM2-3_0_0-B166
644                Al Qoz      ADM2  SDN-ADM2-3_0_0-B130
643              Al Sunut      ADM2  SDN-ADM2-3_0_0-B129
588            Al Tadamon      ADM2   SDN-ADM2-3_0_0-B74
528              Alborgag      ADM2   SDN-ADM2-3_0_0-B14
530               Algolid      ADM2   SDN-ADM2-3_0_0-B16
620               Alwehda      ADM2  SDN-ADM2-3_0_0-B106
675                 Aroma      ADM2  SDN-ADM2-3_0_0-B161
629              Assalaya      ADM2  SDN-ADM2-3_0_0-B115
526                Atbara      ADM2   SDN-ADM2-3_0_0-B12
676          Atbara River      ADM2  SDN-ADM2-3_0_0-B162
589                  Azum      ADM2   SDN-ADM2-3_0_0-B75
641              Babanusa      ADM2  SDN-ADM2-3_0_0-B127
627          Bahr El Arab      ADM2  SDN-ADM2-3_0_0-B113
534                  Bara      ADM2   SDN-ADM2-3_0_0-B20
527                Barbar      ADM2   SDN-ADM2-3_0_0-B13
570               Basonda      ADM2   SDN-ADM2-3_0_0-B56
587                   Bau      ADM2   SDN-ADM2-3_0_0-B73
590                 Beida      ADM2   SDN-ADM2-3_0_0-B76
628                Bielel      ADM2  SDN-ADM2-3_0_0-B114
591               Bindisi      ADM2   SDN-ADM2-3_0_0-B77
135       Blue Nile State      ADM1   SDN-ADM1-3_0_0-B16
659                 Buram      ADM2  SDN-ADM2-3_0_0-B145
129        Central Darfur      ADM1   SDN-ADM1-3_0_0-B10
663                 Dalgo      ADM2  SDN-ADM2-3_0_0-B149
592          Dar El Salam      ADM2   SDN-ADM2-3_0_0-B78
579               Dilling      ADM2   SDN-ADM2-3_0_0-B65
638                 Dimsu      ADM2  SDN-ADM2-3_0_0-B124
529               Dongola      ADM2   SDN-ADM2-3_0_0-B15
674                Dordeb      ADM2  SDN-ADM2-3_0_0-B160
128     East Darfur State      ADM1    SDN-ADM1-3_0_0-B9
574    Eastern El Galabat      ADM2   SDN-ADM2-3_0_0-B60
540     Eastern El Gezira      ADM2   SDN-ADM2-3_0_0-B26
548        Eastern Sennar      ADM2   SDN-ADM2-3_0_0-B34
616              Ed Daein      ADM2  SDN-ADM2-3_0_0-B102
525              Ed Damer      ADM2   SDN-ADM2-3_0_0-B11
617          Ed El Fursan      ADM2  SDN-ADM2-3_0_0-B103
646           El Abassiya      ADM2  SDN-ADM2-3_0_0-B132
678             El Butana      ADM2  SDN-ADM2-3_0_0-B164
546               El Dali      ADM2   SDN-ADM2-3_0_0-B32
671           El Damazine      ADM2  SDN-ADM2-3_0_0-B157
652             El Dindir      ADM2  SDN-ADM2-3_0_0-B138
550             El Douiem      ADM2   SDN-ADM2-3_0_0-B36
568            El Fashaga      ADM2   SDN-ADM2-3_0_0-B54
593             El Fasher      ADM2   SDN-ADM2-3_0_0-B79
679                El Faw      ADM2  SDN-ADM2-3_0_0-B165
657            El Ferdous      ADM2  SDN-ADM2-3_0_0-B143
594            El Geneina      ADM2   SDN-ADM2-3_0_0-B80
555            El Gutaina      ADM2   SDN-ADM2-3_0_0-B41
541          El Hasaheesa      ADM2   SDN-ADM2-3_0_0-B27
556           El Jabalian      ADM2   SDN-ADM2-3_0_0-B42
542            El Kamleen      ADM2   SDN-ADM2-3_0_0-B28
595               El Kuma      ADM2   SDN-ADM2-3_0_0-B81
665             El Kurmuk      ADM2  SDN-ADM2-3_0_0-B151
596              El Malha      ADM2   SDN-ADM2-3_0_0-B82
543           El Manageel      ADM2   SDN-ADM2-3_0_0-B29
523           El Matammah      ADM2    SDN-ADM2-3_0_0-B9
651             El Nehoud      ADM2  SDN-ADM2-3_0_0-B137
565              El Qaneb      ADM2   SDN-ADM2-3_0_0-B51
569            El Quresha      ADM2   SDN-ADM2-3_0_0-B55
656             El Radoom      ADM2  SDN-ADM2-3_0_0-B142
681              El Rahad      ADM2  SDN-ADM2-3_0_0-B167
653           El Roseires      ADM2  SDN-ADM2-3_0_0-B139
642              El Salam      ADM2  SDN-ADM2-3_0_0-B128
632              El Salam      ADM2  SDN-ADM2-3_0_0-B118
647              El Salam      ADM2  SDN-ADM2-3_0_0-B133
597             El Sireaf      ADM2   SDN-ADM2-3_0_0-B83
547              El Souki      ADM2   SDN-ADM2-3_0_0-B33
598           El Taweisha      ADM2   SDN-ADM2-3_0_0-B84
637               El Tina      ADM2  SDN-ADM2-3_0_0-B123
599          Foro Baranga      ADM2   SDN-ADM2-3_0_0-B85
572               Gedaref      ADM2   SDN-ADM2-3_0_0-B58
133         Gedarif State      ADM1   SDN-ADM1-3_0_0-B14
666               Geissan      ADM2  SDN-ADM2-3_0_0-B152
622               Gereida      ADM2  SDN-ADM2-3_0_0-B108
132          Gezira State      ADM1   SDN-ADM1-3_0_0-B13
639              Ghubaysh      ADM2  SDN-ADM2-3_0_0-B125
537    Greater Wad Madani      ADM2   SDN-ADM2-3_0_0-B23
586                Habila      ADM2   SDN-ADM2-3_0_0-B72
600                Habila      ADM2   SDN-ADM2-3_0_0-B86
562               Halayeb      ADM2   SDN-ADM2-3_0_0-B48
664                 Halfa      ADM2  SDN-ADM2-3_0_0-B150
557      Halfa El Jadeeda      ADM2   SDN-ADM2-3_0_0-B43
559          Hamashkoreib      ADM2   SDN-ADM2-3_0_0-B45
566                  Haya      ADM2   SDN-ADM2-3_0_0-B52
580                Heiban      ADM2   SDN-ADM2-3_0_0-B66
515           Jabal Aulia      ADM2    SDN-ADM2-3_0_0-B1
563      Jabiet Al Maadin      ADM2   SDN-ADM2-3_0_0-B49
601            Jebel Moon      ADM2   SDN-ADM2-3_0_0-B87
535      Jebrat El Sheikh      ADM2   SDN-ADM2-3_0_0-B21
582               Kadugli      ADM2   SDN-ADM2-3_0_0-B68
604             Kalimendo      ADM2   SDN-ADM2-3_0_0-B90
519                Karari      ADM2    SDN-ADM2-3_0_0-B5
618                  Kass      ADM2  SDN-ADM2-3_0_0-B104
683               Kassala      ADM2  SDN-ADM2-3_0_0-B169
123         Kassala State      ADM1    SDN-ADM1-3_0_0-B4
626               Katayla      ADM2  SDN-ADM2-3_0_0-B112
602             Kebkabiya      ADM2   SDN-ADM2-3_0_0-B88
575                Keilak      ADM2   SDN-ADM2-3_0_0-B61
521              Khartoum      ADM2    SDN-ADM2-3_0_0-B7
517        Khartoum North      ADM2    SDN-ADM2-3_0_0-B3
131        Khartoum State      ADM1   SDN-ADM1-3_0_0-B12
677         Khashm Ghirba      ADM2  SDN-ADM2-3_0_0-B163
634                Kornoi      ADM2  SDN-ADM2-3_0_0-B120
553                 Kosti      ADM2   SDN-ADM2-3_0_0-B39
603               Kreinik      ADM2   SDN-ADM2-3_0_0-B89
625                 Kubum      ADM2  SDN-ADM2-3_0_0-B111
605                Kulbus      ADM2   SDN-ADM2-3_0_0-B91
606                 Kutum      ADM2   SDN-ADM2-3_0_0-B92
585                Lagawa      ADM2   SDN-ADM2-3_0_0-B71
668              Marshang      ADM2  SDN-ADM2-3_0_0-B154
607                Mellit      ADM2   SDN-ADM2-3_0_0-B93
532                Merawi      ADM2   SDN-ADM2-3_0_0-B18
573        Middle Gedaref      ADM2   SDN-ADM2-3_0_0-B59
608                Mukjar      ADM2   SDN-ADM2-3_0_0-B94
609               Nertiti      ADM2   SDN-ADM2-3_0_0-B95
621               Niteaga      ADM2  SDN-ADM2-3_0_0-B107
126    North Darfur State      ADM1    SDN-ADM1-3_0_0-B7
673           North Delta      ADM2  SDN-ADM2-3_0_0-B159
127  North Kordofan State      ADM1    SDN-ADM1-3_0_0-B8
136        Northern State      ADM1   SDN-ADM1-3_0_0-B17
633                 Nyala      ADM2  SDN-ADM2-3_0_0-B119
630           Nyala North      ADM2  SDN-ADM2-3_0_0-B116
560            Port Sudan      ADM2   SDN-ADM2-3_0_0-B46
571         Qala El Nahal      ADM2   SDN-ADM2-3_0_0-B57
552                 Rabak      ADM2   SDN-ADM2-3_0_0-B38
667        Rahad El Berdi      ADM2  SDN-ADM2-3_0_0-B153
645                Rashad      ADM2  SDN-ADM2-3_0_0-B131
130         Red Sea State      ADM1   SDN-ADM1-3_0_0-B11
581          Reif Ashargi      ADM2   SDN-ADM2-3_0_0-B67
124      River Nile State      ADM1    SDN-ADM1-3_0_0-B5
610                Rokoro      ADM2   SDN-ADM2-3_0_0-B96
558         Rural Kassala      ADM2   SDN-ADM2-3_0_0-B44
611            Saraf Omra      ADM2   SDN-ADM2-3_0_0-B97
545                Sennar      ADM2   SDN-ADM2-3_0_0-B31
125          Sennar State      ADM1    SDN-ADM1-3_0_0-B6
619     Sharg Jabel Marra      ADM2  SDN-ADM2-3_0_0-B105
518         Sharq El Nile      ADM2    SDN-ADM2-3_0_0-B4
623               Shattai      ADM2  SDN-ADM2-3_0_0-B109
669               Sheiria      ADM2  SDN-ADM2-3_0_0-B155
524                Shendi      ADM2   SDN-ADM2-3_0_0-B10
649               Shiekan      ADM2  SDN-ADM2-3_0_0-B135
549                 Singa      ADM2   SDN-ADM2-3_0_0-B35
672                Sinkat      ADM2  SDN-ADM2-3_0_0-B158
612                 Sirba      ADM2   SDN-ADM2-3_0_0-B98
533                Sodari      ADM2   SDN-ADM2-3_0_0-B19
120    South Darfur State      ADM1    SDN-ADM1-3_0_0-B1
121  South Kordofan State      ADM1    SDN-ADM1-3_0_0-B2
538    Southern El Gezira      ADM2   SDN-ADM2-3_0_0-B24
564                Suakin      ADM2   SDN-ADM2-3_0_0-B50
8                   Sudan      ADM0    SDN-ADM0-3_0_0-B1
658                 Sunta      ADM2  SDN-ADM2-3_0_0-B144
577                Talodi      ADM2   SDN-ADM2-3_0_0-B63
636               Tawilla      ADM2  SDN-ADM2-3_0_0-B122
686                Telkok      ADM2  SDN-ADM2-3_0_0-B172
554              Tendalti      ADM2   SDN-ADM2-3_0_0-B40
561                 Tokar      ADM2   SDN-ADM2-3_0_0-B47
670                Tullus      ADM2  SDN-ADM2-3_0_0-B156
662               Um Buru      ADM2  SDN-ADM2-3_0_0-B148
660              Um Dafug      ADM2  SDN-ADM2-3_0_0-B146
520             Um Durman      ADM2    SDN-ADM2-3_0_0-B6
539            Um El Qura      ADM2   SDN-ADM2-3_0_0-B25
648             Um Rawaba      ADM2  SDN-ADM2-3_0_0-B134
516             Umm Badda      ADM2    SDN-ADM2-3_0_0-B2
661            Umm Dukhun      ADM2  SDN-ADM2-3_0_0-B147
578            Umm Durein      ADM2   SDN-ADM2-3_0_0-B64
613           Umm Keddada      ADM2   SDN-ADM2-3_0_0-B99
551            Umm Ramtta      ADM2   SDN-ADM2-3_0_0-B37
536             Wad Banda      ADM2   SDN-ADM2-3_0_0-B22
684          Wad El Helew      ADM2  SDN-ADM2-3_0_0-B170
614            Wadi Salih      ADM2  SDN-ADM2-3_0_0-B100
122     West Darfur State      ADM1    SDN-ADM1-3_0_0-B3
137         West Kurdufan      ADM1   SDN-ADM1-3_0_0-B18
682    Western El Galabat      ADM2  SDN-ADM2-3_0_0-B168
685       Western Kassala      ADM2  SDN-ADM2-3_0_0-B171
134      White Nile State      ADM1   SDN-ADM1-3_0_0-B15
631                Yassin      ADM2  SDN-ADM2-3_0_0-B117
615              Zalingei      ADM2  SDN-ADM2-3_0_0-B101

In [ ]:
dfb_fl_ea['reported_region_places_count'] = dfb_fl_ea['reported region/places'].str.count(',')

C:\Users\HP 820\AppData\Local\Temp\ipykernel_14188\7362825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['reported_region_places_count'] = dfb_fl_ea['reported region/places'].str.count(',')

## replacing GAUL Admin1 Code into GEOB admin2 codes

In [63]:
import geopandas as gp
import pandas as pd
from fuzzywuzzy import process

adm0 = gp.read_file(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\data_sources\202501-impact-events\202501-impact-events\shpfiles\ea_adm0_geoboundaries.shp')
adm1 = gp.read_file(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\data_sources\202501-impact-events\202501-impact-events\shpfiles\ea_adm1_geoboundaries.shp')
adm2 = gp.read_file(r'C:\Users\HP 820\loan_prediction\ea-ibf-climada\data_sources\202501-impact-events\202501-impact-events\shpfiles\ea_adm2_geoboundaries.shp')

db = pd.concat([adm0, adm1, adm2])

db1 = db.drop_duplicates('shapeID')
db1 = db1[db1['shapeGroup'] == 'SDN']
db2 = db1.sort_values('shapeName')
db3 = db2[['shapeName', 'shapeType', 'shapeID']]

print("\nColumns in db3:", db3.columns)

dfb_fl_ea = pd.read_csv(f'{impact_data_path}ea_flood_drought_location_processed.csv')

dfb_fl_ea['reported region/places'] = dfb_fl_ea['reported region/places'].str.strip().str.lower()

print("\nReported Region/Places Values:")
print(dfb_fl_ea['reported region/places'].head())

if not db3.empty:
    db3.loc[:, 'shapeName'] = db3['shapeName'].str.strip().str.lower()

print("\nShapeName Values:")
print(db3['shapeName'].head())

def get_best_match(region, choices):
    match = process.extractOne(region, choices)
    return match[0] if match else None

dfb_fl_ea['best_match'] = dfb_fl_ea['reported region/places'].apply(lambda x: get_best_match(x, db3['shapeName'].tolist()))

print("\nBest Match Results:")
print(dfb_fl_ea[['reported region/places', 'best_match']].head())

merged = pd.merge(dfb_fl_ea, db3, how='left', left_on='best_match', right_on='shapeName')

unmatched_rows = merged[merged['shapeID'].isna()]
print("\nUnmatched Rows:")
print(unmatched_rows)

merged = merged[['sno', 'reported region/places', 'shapeID']]
merged.to_csv(f'{impact_data_path}ea_gaul_geob_adm2_codeshare.csv', index=False)

print("GAUL Admin code mapping and shapeID assignment complete.")

Columns in db3: Index(['shapeName', 'shapeType', 'shapeID'], dtype='object')

Reported Region/Places Values:
0    lower shabelle (juba camp in weydow, garasbale...
1    lower shabelle (juba camp in weydow, garasbale...
2                                          east africa
3        various regions, communities on higher ground
4        various regions, communities on higher ground
Name: reported region/places, dtype: object

ShapeName Values:
522      abu hamed
544     abu houjar
654      abu jabra
576    abu jubaiha
624    abu karinka
Name: shapeName, dtype: object

Best Match Results:
                              reported region/places         best_match
0  lower shabelle (juba camp in weydow, garasbale...           assalaya
1  lower shabelle (juba camp in weydow, garasbale...           assalaya
2                                        east africa  east darfur state
3      various regions, communities on higher ground             sodari
4      various regions, communities on higher ground             sodari

Unmatched Rows:
Empty DataFrame
Columns: [sno, date of event, country, loc_list, loc_list_a, reported region/places, row_idx, report type, best_match, shapeName, shapeType, shapeID]
Index: []

[0 rows x 12 columns]
GAUL Admin code mapping and shapeID assignment complete.

In [75]:
admin1_codes = merged[['sno', 'reported region/places', 'shapeID']]
print(admin1_codes)

admin1_codes.to_csv(r'ea_admin1_codes_mapped.csv', index=False)

    sno                             reported region/places  \
0    63  lower shabelle (juba camp in weydow, garasbale...
1    63  lower shabelle (juba camp in weydow, garasbale...
2   106                                        east africa
3   145      various regions, communities on higher ground
4   145      various regions, communities on higher ground
5   174  42 counties, abyei, northern bahr el ghazal, u...
6   174  42 counties, abyei, northern bahr el ghazal, u...
7   174  42 counties, abyei, northern bahr el ghazal, u...
8   174  42 counties, abyei, northern bahr el ghazal, u...
9   175  38 counties, jonglei, northern bahr el ghazal,...
10  175  38 counties, jonglei, northern bahr el ghazal,...
11  175  38 counties, jonglei, northern bahr el ghazal,...
12  175  38 counties, jonglei, northern bahr el ghazal,...
13  175  38 counties, jonglei, northern bahr el ghazal,...
14  175  38 counties, jonglei, northern bahr el ghazal,...
15  176  northern bahr el ghazal, unity, 42 counties ac...
16  176  northern bahr el ghazal, unity, 42 counties ac...
17  176  northern bahr el ghazal, unity, 42 counties ac...
18  178                                        south sudan
19  217                                  national, somalia
20  217                                  national, somalia
21  231                   mangar ajak, gogrial west county
22  231                   mangar ajak, gogrial west county
23  232  akon international airport, gogrial west count...
24  232  akon international airport, gogrial west count...
25  232  akon international airport, gogrial west count...
26  233           south sudan (white nile and tributaries)
27  233           south sudan (white nile and tributaries)
28  234  nationwide (jonglei, upper nile, unity, warrap...
29  234  nationwide (jonglei, upper nile, unity, warrap...
30  234  nationwide (jonglei, upper nile, unity, warrap...
31  234  nationwide (jonglei, upper nile, unity, warrap...
32  234  nationwide (jonglei, upper nile, unity, warrap...
33  234  nationwide (jonglei, upper nile, unity, warrap...
34  236               addis ababa, rural areas of ethiopia
35  236               addis ababa, rural areas of ethiopia
36  257                      gambella region (4 districts)
37  258                                  kajiado, laikipia
38  258                                  kajiado, laikipia
39  259                            kilifi (mariakani ward)
40  262              lakes state, unity state, sudd region
41  262              lakes state, unity state, sudd region
42  262              lakes state, unity state, sudd region

                shapeID
0   SDN-ADM2-3_0_0-B115
1   SDN-ADM2-3_0_0-B115
2     SDN-ADM1-3_0_0-B9
3    SDN-ADM2-3_0_0-B19
4    SDN-ADM2-3_0_0-B19
5   SDN-ADM2-3_0_0-B126
6   SDN-ADM2-3_0_0-B126
7   SDN-ADM2-3_0_0-B126
8   SDN-ADM2-3_0_0-B126
9   SDN-ADM2-3_0_0-B113
10  SDN-ADM2-3_0_0-B113
11  SDN-ADM2-3_0_0-B113
12  SDN-ADM2-3_0_0-B113
13  SDN-ADM2-3_0_0-B113
14  SDN-ADM2-3_0_0-B113
15  SDN-ADM2-3_0_0-B113
16  SDN-ADM2-3_0_0-B113
17  SDN-ADM2-3_0_0-B113
18    SDN-ADM0-3_0_0-B1
19  SDN-ADM2-3_0_0-B130
20  SDN-ADM2-3_0_0-B130
21    SDN-ADM1-3_0_0-B3
22    SDN-ADM1-3_0_0-B3
23   SDN-ADM1-3_0_0-B16
24   SDN-ADM1-3_0_0-B16
25   SDN-ADM1-3_0_0-B16
26    SDN-ADM0-3_0_0-B1
27    SDN-ADM0-3_0_0-B1
28  SDN-ADM2-3_0_0-B126
29  SDN-ADM2-3_0_0-B126
30  SDN-ADM2-3_0_0-B126
31  SDN-ADM2-3_0_0-B126
32  SDN-ADM2-3_0_0-B126
33  SDN-ADM2-3_0_0-B126
34   SDN-ADM2-3_0_0-B44
35   SDN-ADM2-3_0_0-B44
36  SDN-ADM2-3_0_0-B114
37  SDN-ADM2-3_0_0-B141
38  SDN-ADM2-3_0_0-B141
39   SDN-ADM2-3_0_0-B20
40   SDN-ADM1-3_0_0-B16
41   SDN-ADM1-3_0_0-B16
42   SDN-ADM1-3_0_0-B16

In [76]:
gaul_adm1_dict_db = pd.read_csv(f'{impact_data_path}ea_admin1_codes_mapped.csv')
gaul_adm1_dict = dict(zip(gaul_adm1_dict_db['reported region/places'], gaul_adm1_dict_db['shapeID']))

dfb_fl_ea['gaul_adm1_list'] = dfb_fl_ea['reported region/places'].str.split(';')

dfb_fl_ea_adm1 = dfb_fl_ea[dfb_fl_ea['gaul_adm1_list'].notna()]
dfb_fl_ea_adm1['gaul_adm1_list_int'] = dfb_fl_ea_adm1['gaul_adm1_list'].apply(lambda x: [int(i.strip()) for i in x if i.strip().isdigit()])
dfb_fl_ea_adm1['gaul_adm1_geob'] = dfb_fl_ea_adm1['gaul_adm1_list_int'].apply(lambda x: [gaul_adm1_dict.get(i, None) for i in x])

dfb_fl_ea_adm1_a = dfb_fl_ea_adm1[['sno', 'gaul_adm1_geob']]
dfb_fl_ea_adm1_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sno             43 non-null     int64
 1   gaul_adm1_geob  43 non-null     object
dtypes: int64(1), object(1)
memory usage: 820.0+ bytes

 ## replace adm1 code with adm2 sub codes

In [77]:
import geopandas as gp
import numpy as np

geob_adm1_adm2_filepath = 'C:/Users/HP 820/loan_prediction/202501-impact-events/202501-impact-events/shpfiles/ea_adm2_geoboundaries_adm1_code.shp'

geob_db = gp.read_file(geob_adm1_adm2_filepath)

print(geob_db.columns)

geob_db1 = geob_db[['adm1_shape', 'shapeID']]
geob_db2 = geob_db1.groupby('adm1_shape').agg({'shapeID': lambda x: list(x)})
geob_db3 = geob_db2.reset_index()
geob_db3.columns = ['gaul_adm1_geob', 'shapeID']

geob_db3_dict = dict(zip(geob_db3.gaul_adm1_geob, geob_db3.shapeID))

dfb_fl_ea_adm1_a['geob_adm2'] = dfb_fl_ea_adm1_a['gaul_adm1_geob'].apply(lambda x: [geob_db3_dict[i] for i in x if i in geob_db3_dict])

def flatten(l):
    return [item for sublist in l for item in sublist]

aa_list = []
for idx, row in dfb_fl_ea_adm1_a.iterrows():
    aa = flatten(row['geob_adm2'])
    aa_list.append(aa)

dfb_fl_ea_adm1_a['geob_adm2_list'] = aa_list

dfb_fl_part1 = dfb_fl_ea_adm1_a[['sno', 'geob_adm2_list']]
print(dfb_fl_part1)

Index(['shapeName', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType',
       'adm1_shape', 'geometry'],
      dtype='object')
    sno geob_adm2_list
0    63             []
1    63             []
2   106             []
3   145             []
4   145             []
5   174             []
6   174             []
7   174             []
8   174             []
9   175             []
10  175             []
11  175             []
12  175             []
13  175             []
14  175             []
15  176             []
16  176             []
17  176             []
18  178             []
19  217             []
20  217             []
21  231             []
22  231             []
23  232             []
24  232             []
25  232             []
26  233             []
27  233             []
28  234             []
29  234             []
30  234             []
31  234             []
32  234             []
33  234             []
34  236             []
35  236             []
36  257             []
37  258             []
38  258             []
39  259             []
40  262             []
41  262             []
42  262             []

c:\Users\HP 820\loan_prediction\ea-ibf-climada\venv\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: C:/Users/HP 820/loan_prediction/202501-impact-events/202501-impact-events/shpfiles/ea_adm2_geoboundaries_adm1_code.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(
C:\Users\HP 820\AppData\Local\Temp\ipykernel_14188\3021882481.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_adm1_a['geob_adm2'] = dfb_fl_ea_adm1_a['gaul_adm1_geob'].apply(lambda x: [geob_db3_dict[i] for i in x if i in geob_db3_dict])
C:\Users\HP 820\AppData\Local\Temp\ipykernel_14188\3021882481.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_adm1_a['geob_adm2_list'] = aa_list

## replacing GAUL Admin2 Code into GEOB admin2 codes

In [71]:
dfb_fl_ea['gaul_adm2_list']=dfb_fl_ea['reported region/places'].str.split(';')


impactevents_path='./'

gaul_adm2_dict_db=pd.read_excel(f'{impactevents_path}ea_gaul_geob_adm2_codeshare_v1.xlsx', engine='openpyxl')
gaul_adm2_dict = dict(zip(gaul_adm2_dict_db.gaul_adm2_code, gaul_adm2_dict_db.geob_adm2_shapeID))

gaul_adm2_dict[48481]='TZA-ADM1-3_0_0-B2'
gaul_adm2_dict[48451]='TZA-ADM1-3_0_0-B8'

#48481:TZA-ADM1-3_0_0-B2
#48451:TZA-ADM1-3_0_0-B8

dfb_fl_adm2=dfb_fl_ea[dfb_fl_ea['gaul_adm2_list'].notna()]
dfb_fl_adm2['gaul_adm2_list_int']=dfb_fl_adm2['gaul_adm2_list'].apply(lambda x: [int(i) for i in x])

#dfb_fl_adm2a=dfb_fl_adm2[dfb_fl_adm2['gaul_adm2_list_int']==48481]

dfb_fl_adm2['gaul_adm2_geob'] = dfb_fl_adm2['gaul_adm2_list_int'].apply(lambda x: [gaul_adm2_dict[i] for i in x])

# _b_dict={1:'TZA-ADM1-3_0_0-B2',2:'TZA-ADM1-3_0_0-B8'}

# dfb_fl_adm2['gaul_adm2_geob'] = dfb_fl_adm2['gaul_adm2_geob'].apply(lambda x: [_b_dict[i] for i in x])
# #dfb_dr_a

dfb_fl_part2=dfb_fl_adm2[['Dis No','gaul_adm2_geob']]
dfb_fl_part2.columns=['Dis No','geob_adm2_list']


dfb_fl_part2

FileNotFoundError: [Errno 2] No such file or directory: './ea_gaul_geob_adm2_codeshare_v1.xlsx'

In [72]:
import geopandas as gp
import glob

shpfiles=glob.glob('C:/Users/HP 820/loan_prediction/ea-ibf-climada/data_sources/202501-impact-events/202501-impact-events/shpfiles/geoboundary_code_flood/*.shp')

for shpfl in shpfiles:
    db=gp.read_file(shpfl)
    db

In [73]:
db

,shapeName,shapeISO,...,shapeType,geometry
0,Homa Bay,KE-08,...,ADM1,"POLYGON ((35.02112 -0.41048, 35.02131 -0.41427..."
1,Migori,KE-27,...,ADM1,"POLYGON ((34.73151 -1.38936, 34.70255 -1.37307..."
2,Siaya,KE-38,...,ADM1,"POLYGON ((34.55933 0.07128, 34.55933 0.06768, ..."
3,Busia,KE-04,...,ADM1,"POLYGON ((34.4347 0.73766, 34.43494 0.73406, 3..."
4,Eastern Region,UG-E,...,ADM1,"MULTIPOLYGON (((33.66433 -0.13368, 33.66605 -0..."
5,Central Region,UG-C,...,ADM1,"MULTIPOLYGON (((33.39414 0.23746, 33.39568 0.2..."

## replacing manually added GEOB admin 1 and admin2 codes into common admin2 codes

In [ ]:
import pandas as pd


dfb_fl=pd.read_excel(f'{em_dat_path}ea_flood_missing_location_v2.xlsx', engine='openpyxl')

dfb_fl1=dfb_fl[dfb_fl['geob'].isna()]

dfb_fl2=dfb_fl[dfb_fl['geob'].notna()]
dfb_fl2['geob_list']=dfb_fl2['geob'].str.split(',')

#dfb_dr1['geob_list']=dfb_dr1['geob'].str.split(',')

_ken=gp.read_file(f'geoboundary_code_flood/1998-0443-KEN.shp')

_ken_list=_ken['shapeID'].tolist()

_som94=gp.read_file(f'geoboundary_code_flood/1994-0573-SOM.shp')
_som94_list=_som94['shapeID'].tolist()

_som97=gp.read_file(f'geoboundary_code_flood/1997-0106-SOM.shp')
_som97_list=_som97['shapeID'].tolist()

dfb_fl1.at[38,'geob']=_ken_list
dfb_fl1.at[78,'geob']=_som94_list
dfb_fl1.at[81,'geob']=_som97_list

dfb_fl1a=dfb_fl1.rename(columns={"geob": "geob_list"})

dfb_fl_a=pd.concat([dfb_fl2,dfb_fl1a])
dfb_fl_a


def get_adm1_list(my_list):
    keys = ['ADM1','ADM2']
    aa=[[value for value in my_list if key in value] for key in set(keys)][0]
    bb=[[value for value in my_list if key in value] for key in set(keys)][1]
    #if not aa:
    #    bb=['']
    #else:
    #    bb=aa
    return aa,bb


aa_list=[]
bb_list=[]
for idx,row in dfb_fl_a.iterrows():
    #dfb_dr1.loc[idx,'geob_adm2_list'] = get_adm1_list(row['geob_list'])
    aa,bb=get_adm1_list(row['geob_list'])
    #dfb_dr1.loc[idx,'geob_adm2_list'] =aa
    #print(aa)
    aa_list.append(aa)
    bb_list.append(bb)

dfb_fl_a['geob_adm2_list']=bb_list
dfb_fl_a['geob_adm1_list']=aa_list


# dfb_dr1['geob_adm2'] = dfb_dr1['geob_list'].apply(lambda x: [geob_db3_dict[i] for i in x])
dfb_fl_adm1=dfb_fl_a[['Dis No','geob_adm1_list']]
#dfb_dr1_adm1_a=dfb_dr1_adm1[dfb_dr1_adm1['geob_adm1_list'].notna()]
dfb_fl_adm1_a=dfb_fl_adm1[dfb_fl_adm1['geob_adm1_list'].map(lambda d: len(d)) > 0]
dfb_fl_adm1_a['geob_adm2_list'] = dfb_fl_adm1_a['geob_adm1_list'].apply(lambda x: [geob_db3_dict[i] for i in x])


def flatten(l):
    return [item for sublist in l for item in sublist]

aa_list=[]
for idx,row in dfb_fl_adm1_a.iterrows():
    aa=flatten(row['geob_adm2_list'])
    aa_list.append(aa)
    #dfb_dr1_adm1_a.loc[idx,'geob_adm2_list_a'] = flatten(row['geob_adm2_list'])

dfb_fl_adm1_a['geob_adm2_list_a']=aa_list

dfb_fl_adm1_b=dfb_fl_adm1_a[['Dis No','geob_adm2_list_a']]

dfb_fl2=pd.merge(dfb_fl_a,dfb_fl_adm1_b,on='Dis No',how='left')

dfb_fl2['geob_adm2_list_a'] = dfb_fl2['geob_adm2_list_a'].apply(lambda d: d if isinstance(d, list) else [])

dfb_fl2['geob_adm2_list_a']=(dfb_fl2.geob_adm2_list+dfb_fl2.geob_adm2_list_a).map(set).map(list)

dfb_fl_part3=dfb_fl2[['sno,'geob_adm2_list_a']]

dfb_fl_part3.columns=['sno','geob_adm2_list']

In [ ]:
dfb_parts=pd.concat([dfb_fl_part1,dfb_fl_part2,dfb_fl_part3],axis=0)
dfb_parts1=dfb_parts.drop_duplicates('Dis No')

In [ ]:
df=dfb_parts.groupby('Dis No').agg({'geob_adm2_list': 'sum'})

In [ ]:
df_a=df[df['geob_adm2_list'].map(lambda d: len(d)) > 0]
adisno=df_a.index.tolist()

In [ ]:
#df.to_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/test.csv')

In [ ]:
dfb_fl_ea1=dfb_fl_ea[~dfb_fl_ea['Dis No'].isin(adisno)]
df1=dfb_fl_ea1[['Dis No','Location']]
df1
#df1.to_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/fl_part4_missing_location.csv')

             Dis No                                           Location
33    1993-0503-DJI                                      Djibouti City
41    1990-0582-ETH                                     Gambela region
44    1990-0352-KEN                                                NaN
125   1993-0519-ETH                                   Near Addis Abeba
126   1993-0520-ETH                             Gollam, Gonder regions
155   1990-0016-TZA                              Lindi, Mtwara, Masasi
158   1990-0018-TZA  Moshi, Rombo districts (Kilimanjaro, Rukwa reg...
209   1993-0143-SDN                                         Port Sudan
474   1996-0473-SOM                                                NaN
4123  2018-0477-RWA                                                NaN
4362  2021-0343-ETH                                                NaN
4470  2020-0188-RWA  Gakenke (Northern province), Nyabihu, Muhangad...
4580  2022-0332-SOM                                  Galkayo district
4622  2022-0445-SDN  Kas District (South Darfur Stat); Kassala, Sou...
4631  2022-0258-TZA                           Mbeya and Songwe Regions

# part4 missing admins
1990-0352-KEN - http://erepository.uonbi.ac.ke/bitstream/handle/11295/66135/Alfred%20Opere.pdf?sequence
    
1996-0473-SOM - https://reliefweb.int/report/somalia/fews-bulletin-july-24-1996
    
2018-0477-RWA - https://reliefweb.int/disaster/fl-2018-000029-rwa
    
2021-0343-ETH - https://floodlist.com/tag/ethiopia

Flood catalogs for EA from 1985

https://drought.unl.edu/archive/Documents/NDMC/Workshops/539/Pres/GHA2_Policelli-floods-1.pdf

In [ ]:
import geopandas as gp

_ken=gp.read_file('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/geoboundary_code_flood/1990-0352-KEN.shp')

print(_ken['shapeID'].tolist())

['KEN-ADM2-3_0_0-B3', 'KEN-ADM2-3_0_0-B4', 'KEN-ADM2-3_0_0-B6', 'KEN-ADM2-3_0_0-B7', 'KEN-ADM2-3_0_0-B8', 'KEN-ADM2-3_0_0-B11', 'KEN-ADM2-3_0_0-B12', 'KEN-ADM2-3_0_0-B15', 'KEN-ADM2-3_0_0-B21', 'KEN-ADM2-3_0_0-B24', 'KEN-ADM2-3_0_0-B40', 'KEN-ADM2-3_0_0-B53', 'KEN-ADM2-3_0_0-B55', 'KEN-ADM2-3_0_0-B56', 'KEN-ADM2-3_0_0-B59', 'KEN-ADM2-3_0_0-B62', 'KEN-ADM2-3_0_0-B66', 'KEN-ADM2-3_0_0-B70']

In [ ]:
_som=gp.read_file('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/geoboundary_code_flood/1996-0473-SOM.shp')

print(_som['shapeID'].tolist())

['SOM-ADM2-3_0_0-B5', 'SOM-ADM2-3_0_0-B9', 'SOM-ADM2-3_0_0-B10', 'SOM-ADM2-3_0_0-B13', 'SOM-ADM2-3_0_0-B14', 'SOM-ADM2-3_0_0-B15', 'SOM-ADM2-3_0_0-B16', 'SOM-ADM2-3_0_0-B26', 'SOM-ADM2-3_0_0-B30', 'SOM-ADM2-3_0_0-B33', 'SOM-ADM2-3_0_0-B38', 'SOM-ADM2-3_0_0-B41', 'SOM-ADM2-3_0_0-B43', 'SOM-ADM2-3_0_0-B45', 'SOM-ADM2-3_0_0-B50', 'SOM-ADM2-3_0_0-B53', 'SOM-ADM2-3_0_0-B61', 'SOM-ADM2-3_0_0-B62', 'SOM-ADM2-3_0_0-B65', 'SOM-ADM2-3_0_0-B69']

In [ ]:
_ken1=gp.read_file('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/geoboundary_code_flood/1996-0474-KEN.shp')

print(_ken1['shapeID'].tolist())

['KEN-ADM2-3_0_0-B8', 'KEN-ADM2-3_0_0-B11', 'KEN-ADM2-3_0_0-B12', 'KEN-ADM2-3_0_0-B24', 'KEN-ADM2-3_0_0-B40', 'KEN-ADM2-3_0_0-B49', 'KEN-ADM2-3_0_0-B53', 'KEN-ADM2-3_0_0-B56', 'KEN-ADM2-3_0_0-B62']

## part4 repalce

In [ ]:
import pandas as pd
import geopandas as gp


geob_db=gp.read_file(f'ea_adm2_geoboundaries_adm1_code.shp')
#https://stackoverflow.com/a/54137935/2501953
geob_db1=geob_db[['adm1_shape','shapeID']]
#geob_db2=geob_db1.set_index('adm1_shape')
#geob_db_dict=geob_db1['adm1_shape'].groupby(level=0).apply(lambda x: x.to_dict('shapeID')).to_dict()
geob_db2=geob_db1.groupby('adm1_shape').agg({'shapeID':lambda x: list(x)})
geob_db3=geob_db2.reset_index()
geob_db3.columns=['gaul_adm1_geob','shapeID']
geob_db3_dict = dict(zip(geob_db3.gaul_adm1_geob, geob_db3.shapeID))


dfb_fl=pd.read_csv(f'fl_part4_missing_location_v1.csv')



dfb_fl1=dfb_fl[dfb_fl['geob'].notna()]
dfb_fl1['geob_list']=dfb_fl1['geob'].str.split(',').replace(' ','')



def get_adm1_list(my_list):
    keys = ['ADM1','ADM2']
    aa=[[value for value in my_list if key in value] for key in set(keys)][0]
    bb=[[value for value in my_list if key in value] for key in set(keys)][1]
    #if not aa:
    #    bb=['']
    #else:
    #    bb=aa
    return aa,bb


aa_list=[]
bb_list=[]
for idx,row in dfb_fl1.iterrows():
    #dfb_dr1.loc[idx,'geob_adm2_list'] = get_adm1_list(row['geob_list'])
    aa,bb=get_adm1_list(row['geob_list'])
    #dfb_dr1.loc[idx,'geob_adm2_list'] =aa
    #print(aa)
    aa_list.append(aa)
    bb_list.append(bb)

dfb_fl1['geob_adm2_list']=bb_list
dfb_fl1['geob_adm1_list']=aa_list


# dfb_dr1['geob_adm2'] = dfb_dr1['geob_list'].apply(lambda x: [geob_db3_dict[i] for i in x])
dfb_fl_adm1=dfb_fl1[['Dis No','geob_adm1_list']]
#dfb_dr1_adm1_a=dfb_dr1_adm1[dfb_dr1_adm1['geob_adm1_list'].notna()]
dfb_fl_adm1_a=dfb_fl_adm1[dfb_fl_adm1['geob_adm1_list'].map(lambda d: len(d)) > 0]
dfb_fl_adm1_a['geob_adm2_list'] = dfb_fl_adm1_a['geob_adm1_list'].apply(lambda x: [geob_db3_dict[i] for i in x])


def flatten(l):
    return [item for sublist in l for item in sublist]

aa_list=[]
for idx,row in dfb_fl_adm1_a.iterrows():
    aa=flatten(row['geob_adm2_list'])
    aa_list.append(aa)
    #dfb_dr1_adm1_a.loc[idx,'geob_adm2_list_a'] = flatten(row['geob_adm2_list'])

dfb_fl_adm1_a['geob_adm2_list_a']=aa_list

dfb_fl_adm1_b=dfb_fl_adm1_a[['Dis No','geob_adm2_list_a']]

dfb_fl2=pd.merge(dfb_fl1,dfb_fl_adm1_b,on='Dis No',how='left')

dfb_fl2['geob_adm2_list_a'] = dfb_fl2['geob_adm2_list_a'].apply(lambda d: d if isinstance(d, list) else [])

dfb_fl2['geob_adm2_list_a']=(dfb_fl2.geob_adm2_list+dfb_fl2.geob_adm2_list_a).map(set).map(list)

dfb_fl_part4=dfb_fl2[['Dis No','geob_adm2_list_a']]

dfb_fl_part4.columns=['Dis No','geob_adm2_list']

/opt/conda/lib/python3.9/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [ ]:
dfb_fl_part4

           Dis No                                     geob_adm2_list
0   1993-0503-DJI                                [DJI-ADM2-3_0_0-B8]
1   1990-0582-ETH  [ETH-ADM2-3_0_0-B38, ETH-ADM2-3_0_0-B2, ETH-AD...
2   1990-0352-KEN  [ KEN-ADM2-3_0_0-B40,  KEN-ADM2-3_0_0-B8,  KEN...
3   1993-0519-ETH                               [ETH-ADM2-3_0_0-B48]
4   1993-0520-ETH                               [ETH-ADM2-3_0_0-B63]
5   1990-0016-TZA  [TZA-ADM2-3_0_0-B38, TZA-ADM2-3_0_0-B132, TZA-...
6   1990-0018-TZA  [TZA-ADM2-3_0_0-B18,  TZA-ADM2-3_0_0-B78, TZA-...
7   1993-0143-SDN                               [SDN-ADM2-3_0_0-B46]
8   1993-0005-TZA          [TZA-ADM2-3_0_0-B13,  TZA-ADM2-3_0_0-B30]
9   1993-0157-TZA                               [TZA-ADM2-3_0_0-B30]
10  1994-0013-TZA                               [TZA-ADM2-3_0_0-B10]
11  1996-0474-KEN  [KEN-ADM2-3_0_0-B8,  KEN-ADM2-3_0_0-B40,  KEN-...
12  1997-0328-ETH                               [ETH-ADM2-3_0_0-B21]
13  1995-0317-SOM                               [SOM-ADM2-3_0_0-B68]
14  1996-0473-SOM  [ SOM-ADM2-3_0_0-B14, SOM-ADM2-3_0_0-B69,  SOM...
15  1997-0049-TZA                               [TZA-ADM2-3_0_0-B10]
16  1998-0096-TZA                               [TZA-ADM2-3_0_0-B55]
17  1999-0351-ETH  [ETH-ADM2-3_0_0-B38, ETH-ADM2-3_0_0-B2, ETH-AD...
18  1999-0419-ETH  [ETH-ADM2-3_0_0-B65, ETH-ADM2-3_0_0-B43, ETH-A...
19  1999-0316-SDN                               [SDN-ADM2-3_0_0-B15]
20  1999-0407-SDN                               [SDN-ADM2-3_0_0-B68]
21  2018-0477-RWA                               [RWA-ADM2-3_0_0-B14]
22  2021-0343-ETH                               [ETH-ADM2-3_0_0-B48]
23  2020-0188-RWA  [RWA-ADM2-3_0_0-B14, RWA-ADM2-3_0_0-B10, RWA-A...
24  2022-0332-SOM                                [SOM-ADM2-3_0_0-B4]
25  2022-0445-SDN  [SDN-ADM2-3_0_0-B144, SDN-ADM2-3_0_0-B124, SDN...
26  2022-0258-TZA  [TZA-ADM2-3_0_0-B142, TZA-ADM2-3_0_0-B144, TZA...

In [ ]:
dfb_parts=pd.concat([dfb_fl_part1,dfb_fl_part2,dfb_fl_part3,dfb_fl_part4],axis=0)
#dfb_parts1=dfb_parts.drop_duplicates('Dis No')
df=dfb_parts.groupby('Dis No').agg({'geob_adm2_list': 'sum'})
df['len_of_list'] = df.geob_adm2_list.agg([len])
df['geob_adm2_list1'] = df['geob_adm2_list'].apply(lambda x: list(set(x)))
#df['len_of_list1'] = df.geob_un.agg([len])
df1=df[['geob_adm2_list1']]
df2=df1.reset_index()
df2.columns=['Dis No','geob_adm2_list']
df2.to_excel("em_dat_ea_flood_adm2_v0.xlsx",index=False)

In [ ]:
df2

            Dis No                                     geob_adm2_list
0    1990-0016-TZA  [TZA-ADM2-3_0_0-B38, TZA-ADM2-3_0_0-B132, TZA-...
1    1990-0018-TZA  [TZA-ADM2-3_0_0-B18,  TZA-ADM2-3_0_0-B78, TZA-...
2    1990-0352-KEN  [ KEN-ADM2-3_0_0-B40,  KEN-ADM2-3_0_0-B8,  KEN...
3    1990-0582-ETH  [ETH-ADM2-3_0_0-B38, ETH-ADM2-3_0_0-B2, ETH-AD...
4    1993-0005-TZA  [TZA-ADM2-3_0_0-B13, TZA-ADM2-3_0_0-B30,  TZA-...
..             ...                                                ...
264  2022-0055-RWA  [RWA-ADM2-3_0_0-B17, RWA-ADM2-3_0_0-B14, RWA-A...
265  2022-0232-RWA  [RWA-ADM2-3_0_0-B2, RWA-ADM2-3_0_0-B16, RWA-AD...
266  2022-0258-TZA  [TZA-ADM2-3_0_0-B142, TZA-ADM2-3_0_0-B144, TZA...
267  2022-0332-SOM                                [SOM-ADM2-3_0_0-B4]
268  2022-0445-SDN  [SDN-ADM2-3_0_0-B144, SDN-ADM2-3_0_0-B124, SDN...

[269 rows x 2 columns]